sonar.projectKey=cohort-9-mern-13949-ghulam-backend
sonar.projectName=cohort-9-mern-13949-ghulam-backend
sonar.sources=src
sonar.tests=tests
sonar.sourceEncoding=UTF-8
sonar.exclusions=node_modules/**,coverage/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
